## Topic: Descriptive Statistics for Data Science

#### Week3, move from SQL into statistics, which is a core part of data science. Start with descriptive statistics.

#### That means learning how to summarize data using values such as:

- mean
- median
- mode
- minimum
- maximum
- range
- standard deviation
- quartiles

### Week 3 Day 1

---

In [1]:
# Load the data

import pandas as pd
import numpy as np

df = pd.read_csv("../Data/Processed/telco_churn_cleaned.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [2]:
# Choose the Columns 

df[["tenure", "MonthlyCharges", "TotalCharges"]].head()

   tenure  MonthlyCharges  TotalCharges
0       1           29.85         29.85
1      34           56.95       1889.50
2       2           53.85        108.15
3      45           42.30       1840.75
4       2           70.70        151.65

In [3]:
df[["tenure", "MonthlyCharges", "TotalCharges"]].describe()

            tenure  MonthlyCharges  TotalCharges
count  7032.000000     7032.000000   7032.000000
mean     32.421786       64.798208   2283.300441
std      24.545260       30.085974   2266.771362
min       1.000000       18.250000     18.800000
25%       9.000000       35.587500    401.450000
50%      29.000000       70.350000   1397.475000
75%      55.000000       89.862500   3794.737500
max      72.000000      118.750000   8684.800000

In [4]:
df["MonthlyCharges"].mean()
df["MonthlyCharges"].median()
df["MonthlyCharges"].min()
df["MonthlyCharges"].max()
df["MonthlyCharges"].std()

30.08597388404983

In [5]:
df["tenure"].mean()
df["tenure"].median()
df["tenure"].min()
df["tenure"].max()
df["tenure"].std()

24.545259709263192

In [ ]:
# Calculate Range

monthly_range = df["MonthlyCharges"].max() - df["MonthlyCharges"].min()
tenure_range = df["tenure"].max() - df["tenure"].min()
total_range = df["TotalCharges"].max() - df["TotalCharges"].min()

print("MonthlyCharges range:", monthly_range)
print("Tenure range:", tenure_range)
print("TotalCharges range:", total_range)

MonthlyCharges range: 100.5
Tenure range: 71
TotalCharges range: 8666.0

#### Compare Mean and Median

- mean is close to median means distribution may be more balanced
- mean is much higher or lower than median means distribution may be skewed

In [12]:
stats_df = pd.DataFrame({
    "Column": ["tenure", "MonthlyCharges", "TotalCharges"],
    "Mean": [
        df["tenure"].mean(),
        df["MonthlyCharges"].mean(),
        df["TotalCharges"].mean()
    ],
    "Median": [
        df["tenure"].median(),
        df["MonthlyCharges"].median(),
        df["TotalCharges"].median()
    ]
})

stats_df

           Column         Mean    Median
0          tenure    32.421786    29.000
1  MonthlyCharges    64.798208    70.350
2    TotalCharges  2283.300441  1397.475

In [13]:
df.groupby("Churn")[["tenure", "MonthlyCharges", "TotalCharges"]].mean()

          tenure  MonthlyCharges  TotalCharges
Churn
No     37.650010       61.307408   2555.344141
Yes    17.979133       74.441332   1531.796094

In [14]:
df.groupby("Churn")[["tenure", "MonthlyCharges", "TotalCharges"]].median()

       tenure  MonthlyCharges  TotalCharges
Churn
No       38.0           64.45       1683.60
Yes      10.0           79.65        703.55

### Question for today
1. Do churned customers have lower average tenure? Ans: yes
2. Do churned customers pay higher monthly charges? Ans: yes
3. Do non-churned customers have higher total charges because they stayed longer? Ans: yes
4. Which variable has the largest spread? Ans: TotalCharges

Question 4, the total charge also have a big different, but for the main reason is a customer stays longer, they naturally build up more total charges.

In [15]:
df[["tenure", "MonthlyCharges", "TotalCharges"]].agg(["mean", "median", "min", "max", "std"])

           tenure  MonthlyCharges  TotalCharges
mean    32.421786       64.798208   2283.300441
median  29.000000       70.350000   1397.475000
min      1.000000       18.250000     18.800000
max     72.000000      118.750000   8684.800000
std     24.545260       30.085974   2266.771362

In [16]:
summary_df = pd.DataFrame({
    "Feature": ["tenure", "MonthlyCharges", "TotalCharges"],
    "Mean": [
        df["tenure"].mean(),
        df["MonthlyCharges"].mean(),
        df["TotalCharges"].mean()
    ],
    "Median": [
        df["tenure"].median(),
        df["MonthlyCharges"].median(),
        df["TotalCharges"].median()
    ],
    "Min": [
        df["tenure"].min(),
        df["MonthlyCharges"].min(),
        df["TotalCharges"].min()
    ],
    "Max": [
        df["tenure"].max(),
        df["MonthlyCharges"].max(),
        df["TotalCharges"].max()
    ],
    "Std": [
        df["tenure"].std(),
        df["MonthlyCharges"].std(),
        df["TotalCharges"].std()
    ]
})

summary_df

          Feature         Mean    Median    Min      Max          Std
0          tenure    32.421786    29.000   1.00    72.00    24.545260
1  MonthlyCharges    64.798208    70.350  18.25   118.75    30.085974
2    TotalCharges  2283.300441  1397.475  18.80  8684.80  2266.771362

## Day 1 Statistics Summary

Today, I learned how to use descriptive statistics to summarize numerical variables in the churn dataset. 
I examined the mean, median, minimum, maximum, range, and standard deviation of `tenure`, `MonthlyCharges`, and `TotalCharges`. 
I also compared these statistics across churn groups to better understand customer behavior.