### SQL Practice 

- Part 1: Understand SQL basics

- Part 2: Create a small practice dataset in Python

- Part 3: Write your first SQL queries

- Part 4:Connect SQL thinking to your churn project

---

Part 1: Read the dataset by using SQL statement & syntax

In [ ]:
# Import the library of pandas and sqlite3

import pandas as pd
import sqlite3

In [2]:
df = pd.read_csv("../Data/Processed/telco_churn_cleaned.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
# Create an in-memory SQLite database

conn = sqlite3.connect(":memory:")

In [ ]:
# Load the DataFrame into the SQLite database
df.to_sql("churn_data", conn, index=False, if_exists="replace")

7032

In [5]:
query = """
SELECT *
FROM churn_data
LIMIT 5
"""
pd.read_sql(query, conn)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
# Learn how to use SELECT syntax and select specific columns & limit the number of rows

query = """
SELECT customerID, tenure, MonthlyCharges, Churn
FROM churn_data
LIMIT 10
"""
pd.read_sql(query, conn)

   customerID  tenure  MonthlyCharges Churn
0  7590-VHVEG       1           29.85    No
1  5575-GNVDE      34           56.95    No
2  3668-QPYBK       2           53.85   Yes
3  7795-CFOCW      45           42.30    No
4  9237-HQITU       2           70.70   Yes
5  9305-CDSKC       8           99.65   Yes
6  1452-KIOVK      22           89.10    No
7  6713-OKOMC      10           29.75    No
8  7892-POOKP      28          104.80   Yes
9  6388-TABGU      62           56.15    No

In [7]:
# How to use WHERE syntax

query = """
SELECT customerID, tenure, MonthlyCharges, Churn
FROM churn_data
WHERE Churn = 'Yes'
LIMIT 10
"""
pd.read_sql(query, conn)

   customerID  tenure  MonthlyCharges Churn
0  3668-QPYBK       2           53.85   Yes
1  9237-HQITU       2           70.70   Yes
2  9305-CDSKC       8           99.65   Yes
3  7892-POOKP      28          104.80   Yes
4  0280-XJGEX      49          103.70   Yes
5  4190-MFLUW      10           55.20   Yes
6  8779-QRDMV       1           39.65   Yes
7  1066-JKSGK       1           20.15   Yes
8  6467-CHFZW      47           99.35   Yes
9  8665-UTDHZ       1           30.20   Yes

In [9]:
# Customers with tenure greater than 12 by WHERE syntax

query = """
SELECT customerID, tenure, MonthlyCharges, Churn
FROM churn_data
WHERE tenure > 12
LIMIT 10
"""
pd.read_sql(query, conn)

   customerID  tenure  MonthlyCharges Churn
0  5575-GNVDE      34           56.95    No
1  7795-CFOCW      45           42.30    No
2  1452-KIOVK      22           89.10    No
3  7892-POOKP      28          104.80   Yes
4  6388-TABGU      62           56.15    No
5  9763-GRSKD      13           49.95    No
6  7469-LKBCI      16           18.95    No
7  8091-TTVAX      58          100.35    No
8  0280-XJGEX      49          103.70   Yes
9  5129-JLPIS      25          105.50    No

In [ ]:
# Multiple conditions: Customers with tenure greater than 12 and Churn = 'Yes'

query = """
SELECT customerID, tenure, MonthlyCharges, Contract, Churn
FROM churn_data
WHERE tenure > 12 AND Churn = 'Yes'
LIMIT 10
"""
pd.read_sql(query, conn)

   customerID  tenure  MonthlyCharges        Contract Churn
0  7892-POOKP      28          104.80  Month-to-month   Yes
1  0280-XJGEX      49          103.70  Month-to-month   Yes
2  6467-CHFZW      47           99.35  Month-to-month   Yes
3  8773-HHUOZ      17           64.70  Month-to-month   Yes
4  5380-WJKOV      34          106.35  Month-to-month   Yes
5  9420-LOJKX      15           99.10  Month-to-month   Yes
6  1658-BYGOY      18           95.45  Month-to-month   Yes
7  4598-XLKNJ      25           98.50  Month-to-month   Yes
8  3192-NQECA      68          110.00        Two year   Yes
9  0486-HECZI      55           96.75  Month-to-month   Yes

In [ ]:
#Learn ORDER BY syntax: Customers with the highest monthly charges

query = """
SELECT customerID, MonthlyCharges, Churn
FROM churn_data
ORDER BY MonthlyCharges DESC
LIMIT 10
"""
pd.read_sql(query, conn)

In [11]:
# Learn ORDER BY syntax: Lowest tenure first

query = """
SELECT customerID, tenure, Churn
FROM churn_data
ORDER BY tenure ASC
LIMIT 10
"""
pd.read_sql(query, conn)

   customerID  tenure Churn
0  7590-VHVEG       1    No
1  8779-QRDMV       1   Yes
2  1066-JKSGK       1   Yes
3  8665-UTDHZ       1   Yes
4  7310-EGVHZ       1    No
5  3413-BMNZE       1    No
6  2273-QCKXA       1    No
7  5919-TMRGD       1   Yes
8  2424-WVHPL       1    No
9  6380-ARCEH       1    No

In [13]:
query = """
SELECT customerID, Contract, PaymentMethod, Churn
FROM churn_data
LIMIT 10
"""
pd.read_sql(query, conn)

   customerID        Contract              PaymentMethod Churn
0  7590-VHVEG  Month-to-month           Electronic check    No
1  5575-GNVDE        One year               Mailed check    No
2  3668-QPYBK  Month-to-month               Mailed check   Yes
3  7795-CFOCW        One year  Bank transfer (automatic)    No
4  9237-HQITU  Month-to-month           Electronic check   Yes
5  9305-CDSKC  Month-to-month           Electronic check   Yes
6  1452-KIOVK  Month-to-month    Credit card (automatic)    No
7  6713-OKOMC  Month-to-month               Mailed check    No
8  7892-POOKP  Month-to-month           Electronic check   Yes
9  6388-TABGU        One year  Bank transfer (automatic)    No

In [15]:
query = """
SELECT Contract, Churn
FROM churn_data
WHERE Contract = 'Month-to-month'
LIMIT 10
"""
pd.read_sql(query, conn)

         Contract Churn
0  Month-to-month    No
1  Month-to-month   Yes
2  Month-to-month   Yes
3  Month-to-month   Yes
4  Month-to-month    No
5  Month-to-month    No
6  Month-to-month   Yes
7  Month-to-month    No
8  Month-to-month   Yes
9  Month-to-month    No

In [19]:
# Show the top 10 customers with the highest TotalCharges

query = """
SELECT customerID, TotalCharges, Churn
FROM churn_data
ORDER BY TotalCharges DESC
LIMIT 10
"""
pd.read_sql(query, conn)

   customerID  TotalCharges Churn
0  2889-FPWRM       8684.80   Yes
1  7569-NMZYQ       8672.45    No
2  9739-JLPQJ       8670.10    No
3  9788-HNGUT       8594.40    No
4  8879-XUAHX       8564.75    No
5  9924-JPRMC       8547.15    No
6  0675-NCDYU       8543.25    No
7  6650-BWFRT       8529.50    No
8  0164-APGRB       8496.70    No
9  1488-PBLJN       8477.70    No

In [22]:
#  Show 10 customers who use Fiber optic and have MonthlyCharges greater than 80

query = """
SELECT customerID, TotalCharges, MonthlyCharges, InternetService, Churn
FROM churn_data
WHERE InternetService = 'Fiber optic' AND MonthlyCharges > 80
LIMIT 10
"""
pd.read_sql(query, conn)

   customerID  TotalCharges  MonthlyCharges InternetService Churn
0  9305-CDSKC        820.50           99.65     Fiber optic   Yes
1  1452-KIOVK       1949.40           89.10     Fiber optic    No
2  7892-POOKP       3046.05          104.80     Fiber optic   Yes
3  8091-TTVAX       5681.10          100.35     Fiber optic    No
4  0280-XJGEX       5036.30          103.70     Fiber optic   Yes
5  5129-JLPIS       2686.05          105.50     Fiber optic    No
6  3655-SNQYZ       7895.15          113.25     Fiber optic    No
7  9959-WOFKT       7382.25          106.70     Fiber optic    No
8  4183-MYFRB       1862.90           90.05     Fiber optic    No
9  6467-CHFZW       4749.15           99.35     Fiber optic   Yes

### Which customers are paying the most each month? 
---

In [ ]:
# Which customers are paying the most each month? 
# The answer is 7569-NMZYQ

query = """
SELECT customerID, TotalCharges, MonthlyCharges, InternetService, Churn
FROM churn_data
ORDER BY MonthlyCharges DESC
LIMIT 10
"""
pd.read_sql(query, conn)

   customerID  TotalCharges  MonthlyCharges InternetService Churn
0  7569-NMZYQ       8672.45          118.75     Fiber optic    No
1  8984-HPEMB       8477.60          118.65     Fiber optic    No
2  5989-AXPUC       7990.05          118.60     Fiber optic    No
3  5734-EJKXG       7365.70          118.60     Fiber optic    No
4  8199-ZLLSA       7804.15          118.35     Fiber optic   Yes
5  9924-JPRMC       8547.15          118.20     Fiber optic    No
6  2889-FPWRM       8684.80          117.80     Fiber optic   Yes
7  3810-DVDQQ       8308.90          117.60     Fiber optic    No
8  9739-JLPQJ       8670.10          117.50     Fiber optic    No
9  2302-ANTDP       5438.90          117.45     Fiber optic   Yes

### Are churned customers more likely to be on month-to-month contracts?

In [24]:
# Are churned customers more likely to be on month-to-month contracts?

query = """
SELECT customerID, Contract, Churn
FROM churn_data
WHERE Churn = 'Yes' 
ORDER BY Contract
LIMIT 10
"""
pd.read_sql(query, conn)

   customerID        Contract Churn
0  3668-QPYBK  Month-to-month   Yes
1  9237-HQITU  Month-to-month   Yes
2  9305-CDSKC  Month-to-month   Yes
3  7892-POOKP  Month-to-month   Yes
4  0280-XJGEX  Month-to-month   Yes
5  4190-MFLUW  Month-to-month   Yes
6  8779-QRDMV  Month-to-month   Yes
7  1066-JKSGK  Month-to-month   Yes
8  6467-CHFZW  Month-to-month   Yes
9  8665-UTDHZ  Month-to-month   Yes

In [ ]:
query = """
SELECT 
    Contract,
    COUNT(*) AS churned_customers,
    ROUND(COUNT(*) * 100.0 / (
        SELECT COUNT(*)
        FROM churn_data
        WHERE Churn = 'Yes'
    ), 2) AS percentage
FROM churn_data
WHERE Churn = 'Yes'
GROUP BY Contract
ORDER BY churned_customers DESC
"""

pd.read_sql(query, conn)

         Contract Churn  churned_customers  percentage
0  Month-to-month   Yes               1655       88.55
1        One year   Yes                166        8.88
2        Two year   Yes                 48        2.57

Yes, Most of the customers more likely to be on month-to-month contracts.

### Are high-paying fiber optic users more likely to churn?
---

In [ ]:
# Are high-paying fiber optic users more likely to churn?

query = """
SELECT 
    InternetService, MonthlyCharges, Churn
FROM churn_data
WHERE InternetService = 'Fiber optic'
  AND MonthlyCharges > 100
ORDER BY MonthlyCharges DESC
LIMIT 10
"""   

pd.read_sql(query, conn)

  InternetService  MonthlyCharges Churn
0     Fiber optic          118.75    No
1     Fiber optic          118.65    No
2     Fiber optic          118.60    No
3     Fiber optic          118.60    No
4     Fiber optic          118.35   Yes
5     Fiber optic          118.20    No
6     Fiber optic          117.80   Yes
7     Fiber optic          117.60    No
8     Fiber optic          117.50    No
9     Fiber optic          117.45   Yes

In [41]:
query = """
SELECT 
    Churn,
    COUNT(*) AS customer_count,
    ROUND(
        COUNT(*) * 100.0 / (
            SELECT COUNT(*)
            FROM churn_data
            WHERE InternetService = 'Fiber optic'
              AND MonthlyCharges > 100
        ), 2
    ) AS percentage
FROM churn_data
WHERE InternetService = 'Fiber optic'
  AND MonthlyCharges > 100
GROUP BY Churn
ORDER BY percentage DESC
"""

pd.read_sql(query, conn)

  Churn  customer_count  percentage
0    No             649       71.95
1   Yes             253       28.05

### Which customers have stayed the longest?
---

In [ ]:
query = """
SELECT customerID, tenure, Churn
FROM churn_data
ORDER BY tenure DESC
LIMIT 10
"""
pd.read_sql(query, conn)

   customerID  tenure Churn
0  5248-YGIJN      72    No
1  6234-RAAPL      72    No
2  5954-BDFSG      72    No
3  0526-SXDJP      72    No
4  9848-JQJTX      72    No
5  6728-DKUCO      72    No
6  2848-YXSMW      72    No
7  6734-PSBAW      72    No
8  3146-MSEGF      72    No
9  5997-OPVFA      72    No

The longest-staying customers have a tenure of 72 months. In the top 10 results, all customers have Churn = No, which means they are still with the company. This suggests that customers with longer tenure are less likely to churn.

### Day 1 SQL Summary

Today, I learned how to use basic SQL queries for data analysis. 
I practiced `SELECT`, `WHERE`, `ORDER BY`, and `LIMIT` using the cleaned churn dataset in SQLite. 
These commands help me filter, sort, and retrieve useful data to answer business questions.

---